sudo: false
language: node_js
matrix:
    fast_finish: true
    allow_failures:
        - node_js: 4
branches:
  except:
    - demo
node_js:
    - 0.10
    - 0.12
    - 4
env:
    global:
        - NODE_ENV=test
services:
    - couchdb
cache:
    directories:
        - node_modules
addons:
    apt:
        packages:
            - netstat

before_install:
    - git clone git://github.com/cozy/cozy-data-system.git
    - cd cozy-data-system
    - npm install forever coffee-script -g
    - npm install # data-system
    - pwd
    - NAME=data-system TOKEN=token forever start -o forever-ds.log build/server.js
    - ps aux | grep server.js
    - sleep 5
    - curl http://localhost:9101/
    - cd ..
    - cd client
    - npm install
    - cd ..
    - npm install
    - npm run build:server
    - export NAME=proxy
    - export TOKEN=token

after_failure:
    - pwd
    - ps aux | grep server.js
    - netstat -lntp
    - cat ~/cozy-data-system/forever-ds.log
    - cat ~/cozy-proxy/forever-proxy.log
    - curl http://localhost:9101/
    - curl http://localhost:9104/
